//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetTracking_v1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetLocation
    {
        public int LocationID { get; set; }
        public long DistrictID { get; set; }
        public string place { get; set; }
    
        public virtual District District { get; set; }
    }
}
