//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetTracking_v1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.Issuances = new HashSet<Issuance>();
        }
    
        public int Asset_No { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Asset_Name { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Serial_No { get; set; }
        public System.DateTime Acquired_Date { get; set; }
        public long DistrictID { get; set; }
        public int Designated_Office { get; set; }
        public string Designated_Department { get; set; }
        public string Room_No { get; set; }
        public string custodian { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public string Source_of_funds { get; set; }
        public Nullable<int> Landing_cost { get; set; }
        public string EditUser { get; set; }
        public Nullable<long> Quantity { get; set; }
    
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issuance> Issuances { get; set; }
    }
}
