//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetTracking_v1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public District()
        {
            this.Assets = new HashSet<Asset>();
            this.AssetLocations = new HashSet<AssetLocation>();
            this.Requests = new HashSet<Request>();
        }
    
        public long DistrictId { get; set; }
        public string Name { get; set; }
        public string CityName { get; set; }
        public Nullable<System.DateTime> TimeOfLastDownload { get; set; }
        public Nullable<System.DateTime> TimeOfLastUpload { get; set; }
        public long RegionId { get; set; }
        public string EditUser { get; set; }
        public string EditMachine { get; set; }
        public System.DateTime DateOfEdit { get; set; }
        public int Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetLocation> AssetLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
