//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetTracking_v1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issuance
    {
        public int Issuance_ID { get; set; }
        public Nullable<int> Asset_No { get; set; }
        public Nullable<System.DateTime> Date_of_Issue { get; set; }
        public string Issued_to { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Issued_by { get; set; }
    
        public virtual Asset Asset { get; set; }
    }
}
