//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetTracking_v1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestId { get; set; }
        public System.DateTime DateRequested { get; set; }
        public long SourceDistrict { get; set; }
        public string SourceLocation { get; set; }
        public string DestinationDistrict { get; set; }
        public string DestinationLocation { get; set; }
        public string ItemName { get; set; }
        public string ItemStatus { get; set; }
        public string ReasonForTransfer { get; set; }
        public string EditUser { get; set; }
        public string Status { get; set; }
    
        public virtual District District { get; set; }
    }
}
